name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up go toolchain
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Build application
        run: ./scripts/buildprod.sh

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'us-central1-docker.pkg.dev/notely-454116/notely-ar-repo'
          service_account: 'cloud-run-deployer@notely-454116.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: 'Build and push image to GCP AR'
        run: 'gcloud builds submit --tag us-central1-docker.pkg.dev/notely-454116/notely-ar-repo/notely:latest .'
